extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
plugins:
  - react
rules:
  react/jsx-boolean-value:
    - error
    - always
  react/no-multi-comp: error
  react/self-closing-comp: error
  react/prop-types: 0
settings:
  react:
    version: detect
globals:
  graphql: false
env:
  browser: true
  node: true
parser: babel-eslint
