extends:
  - eslint:recommended
  - next
  - plugin:prettier/recommended
rules:
  react/jsx-boolean-value: [error, always]
  react/no-multi-comp: error
  react/self-closing-comp: error
  react/prop-types: 0
settings:
  react:
    version: detect
env:
  browser: true
  node: true
