files:
  ignore:
    - 'node_modules/**/*'
rules:
  attribute-quotes:
    - 2
  bem-depth:
    - 2
    - max-depth: 2
  border-zero:
    - 2
    - convention: none
  brace-style:
    - 2
    - style: 1tbs
  class-name-format:
    - 2
    - convention: camelcase
      allow-leading-underscore: false
  clean-import-paths:
    - 0
  declarations-before-nesting:
    - 2
  empty-args:
    - 2
    - include: false
  empty-line-between-blocks:
    - 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - allow-leading-underscore: true
      convention: camelcase
  hex-length:
    - 2
    - style: long
  hex-notation:
    - 2
    - style: lowercase
  id-name-format:
    - 2
    - convention: camelcase
      allow-leading-underscore: false
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  max-file-line-count: 0
  max-line-length:
    - 1
    - length: 80
  mixin-name-format:
    - 2
    - allow-leading-underscore: true
      convention: camelcase
  mixins-before-declarations: 2
  nesting-depth:
    - 2
    - max-depth: 3
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 1
  no-combinators: 0
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 2
  no-url-protocols: 0 # deprecated
  no-vendor-prefixes: 2
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  placeholder-name-format:
    - 2
    - convention: camelcase
  property-sort-order:
    - 1
    - order: smacss
  # TODO: cut down on this list
  property-units:
    - 2
    - global:
        - ch
        - em
        - ex
        - rem
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property: {}
  quotes:
    - 2
    - style: single
  shorthand-values:
    - 2
    - allowed-shorthands:
        - 1
        - 2
        - 3
  single-line-per-selector: 2
  space-after-bang: 0
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 0
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property:
    - 0
    - properties: []
  variable-name-format:
    - 2
    - allow-leading-underscore: false
      convention: camelcase
  zero-unit: 2
